import { Schema } from '@types';

export const medicalQuestionnaireSchema: Schema = {
  id: '1',
  version: '1.0',
  components: [
    {
      id: 'name4',
      formKey: 'name',
      type: 'input-field',
      label: 'Full Name',
      disabled: false,
      value: '',
      layout: { col: { default: 24 } },
    },
    {
      id: 'email5',
      formKey: 'email',
      type: 'email-field',
      label: 'Email',
      disabled: false,
      value: '',
      layout: { col: { default: 24 } },
    },
    {
      id: 'phone5',
      formKey: 'phone',
      type: 'phone-field',
      label: 'Phone Number',
      disabled: false,
      value: '',
      layout: { col: { default: 24 } },
    },
    {
      id: 'dob1',
      formKey: 'dob',
      type: 'input-field',
      label: 'Date of Birth',
      disabled: false,
      value: '',
      customProperties: { type: 'date' },
      layout: { col: { default: 24 } },
    },
    {
      id: 'gender2',
      formKey: 'gender',
      type: 'radio-field',
      label: 'Gender',
      disabled: false,
      options: [
        { label: 'Male', value: 'male' },
        { label: 'Female', value: 'female' },
        { label: 'Other', value: 'other' },
      ],
      value: 'other',
      layout: { col: { default: 24 } },
    },
    {
      id: 'address2',
      formKey: 'address',
      type: 'textarea-field',
      label: 'Address',
      disabled: false,
      value: '',
      layout: { col: { default: 24 } },
    },
    {
      id: 'medicalHistory1',
      formKey: 'medicalHistory',
      type: 'textarea-field',
      label: 'Medical History',
      disabled: false,
      value: '',
      layout: { col: { default: 24 } },
    },
    {
      id: 'allergies1',
      formKey: 'allergies',
      type: 'checkbox-field',
      label: 'Allergies',
      disabled: false,
      options: [
        { label: 'Peanuts', value: 'peanuts' },
        { label: 'Dairy', value: 'dairy' },
        { label: 'Gluten', value: 'gluten' },
        { label: 'Other', value: 'other' },
      ],
      value: [],
      layout: { col: { default: 24 } },
    },
    {
      id: 'medications1',
      formKey: 'medications',
      type: 'textarea-field',
      label: 'Current Medications',
      disabled: false,
      value: '',
      layout: { col: { default: 24 } },
    },
    {
      id: 'insuranceProvider1',
      formKey: 'insuranceProvider',
      type: 'input-field',
      label: 'Insurance Provider',
      disabled: false,
      value: '',
      layout: { col: { default: 24 } },
    },
    {
      id: 'policyNumber1',
      formKey: 'policyNumber',
      type: 'input-field',
      label: 'Policy Number',
      disabled: false,
      value: '',
      layout: { col: { default: 24 } },
    },
    {
      id: 'emergencyContact1',
      formKey: 'emergencyContact',
      type: 'input-field',
      label: 'Emergency Contact',
      disabled: false,
      value: '',
      layout: { col: { default: 24 } },
    },
    {
      id: 'emergencyContactPhone1',
      formKey: 'emergencyContactPhone',
      type: 'phone-field',
      label: 'Emergency Contact Phone Number',
      disabled: false,
      value: '',
      layout: { col: { default: 24 } },
    },
    {
      id: 'submit5',
      formKey: 'submit',
      type: 'button',
      text: 'Submit',
      layout: { col: { default: 24 } },
    },
  ],
};

export const employeeAnnualReviewSchema: Schema = {
  id: '2',
  version: '1.0',
  components: [
    {
      id: 'employeeName1',
      formKey: 'employeeName',
      type: 'input-field',
      label: 'Employee Name',
      placeholder: 'Your name',
      disabled: false,
      value: '',
      layout: { col: { default: 24 } },
    },
    {
      id: 'email6',
      formKey: 'email',
      type: 'email-field',
      label: 'Email',
      placeholder: 'example@gmail.com',
      disabled: false,
      value: '',
      layout: { col: { default: 24 } },
    },
    {
      id: 'department1',
      formKey: 'department',
      type: 'input-field',
      label: 'Department',
      placeholder: 'Department name',
      disabled: false,
      value: '',
      layout: { col: { default: 24 } },
    },
    {
      id: 'reviewPeriod1',
      formKey: 'reviewPeriod',
      type: 'input-field',
      label: 'Review Period',
      disabled: false,
      value: '',
      customProperties: { type: 'date' },
      layout: { col: { default: 24 } },
    },
    {
      id: 'performanceRating1',
      formKey: 'performanceRating',
      type: 'radio-field',
      label: 'Performance Rating',
      disabled: false,
      options: [
        { label: 'Excellent', value: 'excellent' },
        { label: 'Good', value: 'good' },
        { label: 'Average', value: 'average' },
        { label: 'Poor', value: 'poor' },
      ],
      value: 'good',
      layout: { col: { default: 24 } },
    },
    {
      id: 'goalsAchieved1',
      formKey: 'goalsAchieved',
      type: 'checkbox-field',
      label: 'Goals Achieved',
      disabled: false,
      options: [
        { label: 'Met all deadlines', value: 'deadlines' },
        { label: 'Exceeded expectations', value: 'expectations' },
        { label: 'Improved skills', value: 'skills' },
      ],
      value: [],
      layout: { col: { default: 24 } },
    },
    {
      id: 'areasForImprovement1',
      formKey: 'areasForImprovement',
      type: 'textarea-field',
      label: 'Areas for Improvement',
      disabled: false,
      value: '',
      layout: { col: { default: 24 } },
    },
    {
      id: 'trainingRequired1',
      formKey: 'trainingRequired',
      type: 'textarea-field',
      label: 'Training Required',
      disabled: false,
      value: '',
      layout: { col: { default: 24 } },
    },
    {
      id: 'additionalComments1',
      formKey: 'additionalComments',
      type: 'textarea-field',
      label: 'Additional Comments',
      disabled: false,
      value: '',
      layout: { col: { default: 24 } },
    },
    {
      id: 'reviewerName1',
      formKey: 'reviewerName',
      type: 'input-field',
      label: 'Reviewer Name',
      placeholder: "Enter the reviewer's name",
      disabled: false,
      value: '',
      layout: { col: { default: 24 } },
    },
    {
      id: 'submit6',
      formKey: 'submit',
      type: 'button',
      text: 'Submit Review',
      layout: { col: { default: 24 } },
    },
  ],
};

export const personalSchema: Schema = {
  id: '3',
  version: '1.0',
  layout: {
    colsSpanPx: { default: 20, xxl: 40 },
    rowsSpanPx: { default: 16 },
  },
  components: [
    {
      id: '0',
      type: 'text',
      text: 'Header text',
      layout: {
        col: {
          default: 24,
        },
      },
    },
    {
      id: '1',
      formKey: 'personal-info',
      type: 'group',
      layout: {
        col: {
          default: 24,
        },
      },
      components: [
        {
          id: '1-1',
          formKey: 'first-name',
          type: 'input-field',
          label: 'First Name',
          value: 'John',
          placeholder: 'Enter your first name',
          layout: {
            col: {
              default: 5,
              xxl: 12,
            },
          },
        },
        {
          id: '1-2',
          formKey: 'last-name',
          type: 'input-field',
          label: 'Last Name',
          value: 'Doe',
          placeholder: 'Enter your last name',
          layout: {
            col: {
              default: 10,
              xxl: 12,
            },
          },
        },
        {
          id: '1-3',
          formKey: 'email',
          type: 'email-field',
          label: 'Email',
          value: 'johndoe@example.com',
          placeholder: 'Enter your email',
          layout: {
            col: {
              default: 9,
              sm: 2,
            },
          },
        },
      ],
    },
    {
      id: '2',
      formKey: 'preferences',
      type: 'group',
      layout: {
        col: {
          default: 24,
        },
      },
      components: [
        {
          id: '2-1',
          formKey: 'favorite-color',
          type: 'select-field',
          label: 'Favorite Color',
          options: [
            { label: 'Red', value: 'red' },
            { label: 'Green', value: 'green' },
            { label: 'Blue', value: 'blue' },
          ],
          value: ['blue'],
          placeholder: 'Select your favorite color',
          layout: {
            col: {
              default: 24,
            },
          },
        },
        {
          id: '2-2',
          formKey: 'subscribe',
          type: 'checkbox-field',
          label: 'Subscribe to newsletter',
          options: [
            { label: 'Yes', value: 'yes' },
            { label: 'No', value: 'no' },
          ],
          value: ['yes'],
          layout: {
            col: {
              default: 24,
            },
          },
        },
        {
          id: '2-3',
          formKey: 'sex',
          type: 'radio-field',
          label: 'Your sex',
          options: [
            { label: 'Male', value: 'male' },
            { label: 'Female', value: 'female' },
          ],
          value: 'male',
          layout: {
            col: {
              default: 24,
            },
          },
        },
      ],
    },
    {
      id: '3',
      formKey: 'phone',
      type: 'phone-field',
      label: 'Phone Number',
      value: '+1234567890',
      placeholder: 'Enter your phone number',
      layout: {
        col: {
          default: 24,
        },
      },
    },
    {
      id: '4',
      formKey: 'article',
      type: 'textarea-field',
      label: 'Article',
      value: 'This is a sample article.',
      placeholder: 'Enter your article',
      layout: {
        col: {
          default: 24,
        },
      },
    },
    {
      id: '5',
      formKey: 'submit',
      type: 'button',
      text: 'Submit',
      layout: {
        col: {
          default: 24,
        },
      },
    },
  ],
};
